function(fib)
set(TARGET test_fibonacci)
add_executable(${TARGET} test_fibonacci.cpp)
target_link_libraries(${TARGET} PUBLIC rbl serial)
add_test(${TARGET} ${TARGET})
endfunction()

function(line_generator)
set(TARGET test_line_gen)
add_executable(${TARGET} test_line_generator.cpp)
target_link_libraries(${TARGET} PUBLIC rbl serial)
add_test(${TARGET} ${TARGET})
endfunction()

function(callback2coroutine)
set(TARGET callback2coroutine)
add_executable(${TARGET} test_callback2coroutine_01.cpp)
target_link_libraries(${TARGET} PUBLIC rbl serial)
add_test(${TARGET} ${TARGET})
endfunction()

fib()
line_generator()
callback2coroutine()
